### ISSUE TITLE
gatsby v2.0 migration

### ISSUE THREAD

**Issue by Jamsek-m** [wiziple/gatsby-starter-default-intl#4]
Hello,
are there any plans for migration to Gatsby v2.0?

I am trying to get it to work, but I am having some problems regarding context (since it was deprecated in react and it should use ContextProvider now instead)

**Comment by tomekskuta** [comment]
Hey guys!
Check out my intl starter for Gatsby v2. It's based on this intl starter and Gatsby default starter:

https://github.com/tomekskuta/gatsby-starter-intl

:)

**Comment by wiziple** [comment]
Please check the updated repo 👍
